services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gabook-laravel
    container_name: gabook-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor  # Añade esto para persistencia
      - /var/www/html/node_modules
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      # ... tus otras variables de entorno ...
    command: >
      sh -c "
      php artisan key:generate &&
      php artisan config:clear &&
      php artisan cache:clear &&
      chmod -R 775 storage bootstrap/cache &&
      chown -R www-data:www-data storage bootstrap/cache &&
      apache2-foreground
      "
    networks:
      - gabook-network
